version: "3.9"

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://giaypjxu:ud0s86cKbllUBuFNafts96iNLXjFebcQ@tiny.db.elephantsql.com/giaypjxu
      PORT: 8000
    ports:
      - "8000:8000"
    